export const GET_AIRPORT_LIST = 'GET_AIRPORT_LIST';
export type GET_AIRPORT_LIST = typeof GET_AIRPORT_LIST;

export const GET_AIRPORT_LIST_SUCCESS = 'GET_AIRPORT_LIST_SUCCESS';
export type GET_AIRPORT_LIST_SUCCESS = typeof GET_AIRPORT_LIST_SUCCESS;

export const GET_AIRPORT_LIST_FAILURE = 'GET_AIRPORT_LIST_FAILURE';
export type GET_AIRPORT_LIST_FAILURE = typeof GET_AIRPORT_LIST_FAILURE;

export const GET_ALL_FLIGHT_DETAILS_LIST = 'GET_ALL_FLIGHT_DETAILS_LIST';
export type GET_ALL_FLIGHT_DETAILS_LIST = typeof GET_ALL_FLIGHT_DETAILS_LIST;

export const GET_ALL_FLIGHT_DETAILS_LIST_SUCCESS = 'GET_ALL_FLIGHT_DETAILS_LIST_SUCCESS';
export type GET_ALL_FLIGHT_DETAILS_LIST_SUCCESS = typeof GET_ALL_FLIGHT_DETAILS_LIST_SUCCESS;

export const GET_ALL_FLIGHT_DETAILS_LIST_FAILURE = 'GET_ALL_FLIGHT_DETAILS_LIST_FAILURE';
export type GET_ALL_FLIGHT_DETAILS_LIST_FAILURE = typeof GET_ALL_FLIGHT_DETAILS_LIST_FAILURE;

export const RESET_AIRPORT_CONNECTION_BUILDER_DATA = 'RESET_AIRPORT_CONNECTION_BUILDER_DATA';
export type RESET_AIRPORT_CONNECTION_BUILDER_DATA = typeof RESET_AIRPORT_CONNECTION_BUILDER_DATA;

